modLoader = "javafml"
loaderVersion = "[47,)"
license = "Insert License Here"

[[mods]]
modId = "hostile_boats"
version = "${version}"
displayName = "Hostile Boats"
authors = "shiftjis"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.hostile_boats]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hostile_boats]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hostile_boats]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
